### ISSUE TITLE
Why mask() compares targets against 1 rather than 0

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/grounded-video-description#11]
Hi, I'm wondering for the function `mask()` in `misc.transformer` why it's comparing `targets` against 1? since the padded (both at the front and end of the sentence) value is 0, shouldn't it compare it against 0? Thanks.

**Comment by LuoweiZhou** [comment]
Hi @CaesarPan, thank you for the feedback and you're right. The Transformer part of this repo is referred to this [repo](https://github.com/salesforce/densecap/blob/master/model/transformer.py), which uses a different tokenization and numericalization (0: <unk>, 1: <pad>, 2: <init>, 3: <eos>). In their case, the `[targets](https://github.com/facebookresearch/grounded-video-description/blob/master/misc/transformer.py#L53)` are compared against 1 (i.e., <pad>). However, in our case, it should be 0 (as our <pad> is 0). As a result, the losses on the <pad> tokens are computed by mistake.

I've fixed this issue [here](https://github.com/facebookresearch/grounded-video-description/commit/7b291073fe33956614441bb1d7566ccc344ac925). Note that this would not affect the experiments in the paper on Masked Transformer since the Transformer part of this repo is for reference only, all the experiments are done with the original [DenseCap](http://openaccess.thecvf.com/content_cvpr_2018/CameraReady/0037.pdf) implementation.

**Comment by CaesarPan** [comment]
i see. thanks for fixing that!
