### ISSUE TITLE
Steps to generate a caption from a video file

### ISSUE THREAD

**Issue by sgdgp** [facebookresearch/grounded-video-description#17]
Hi, can someone tell the steps to do/ python script to run in order to generate the caption of a video file I have.
What inputs do I need to prepare and which function to invoke ? I don't need any evaluation script to run for this case, just the prediction

**Comment by LuoweiZhou** [comment]
@sgdgp You can refer to this issue: https://github.com/facebookresearch/grounded-video-description/issues/12

**Comment by sgdgp** [comment]
@LuoweiZhou Thanks. I am trying to follow the steps. currently stuck at setting up the caffe-action repository.

**Comment by sgdgp** [comment]
@LuoweiZhou Hi, I am facing problem in getting the frame feature vectors using the caffe-action and the anet feature extraction code.
Even with a single frame  of size 224 x 224 x 3 it shows out of memory in gpu which is very strange !

Could you enlighten me if there is some basic issue which causes this ? Or if there is any other way to get features without using caffe at all ?

**Comment by LuoweiZhou** [comment]
@sgdgp When you say "a single frame" you mean you're extracting the appearance feature for a single RGB frame? Could you elaborate more on this? Since to extract the motion feature, you need five consecutive frames.
If you want to use our pre-trained models, you will have to use the same feature extraction code.
