### ISSUE TITLE
In inference-only mode, how to split my own video into several segments to represent each event?

### ISSUE THREAD

**Issue by AarynBaelish** [facebookresearch/grounded-video-description#22]
In the paper:
> In video description, we augment the global feature with segment positional information (i.e., total number of segments, segment index, start time and end time), which is empirically important.

I confused where the segment information `start time` and `end time` come from.

I have extracted features from my own video already, and can generate sentence. But it just generates one sentence for one video. So, how to split several events for one video? OR, how to get the start and end time information to represent each event from a new video?

**Comment by LuoweiZhou** [comment]
@AarynBaelish `start time`, `end time` and all others result from the data format itself since videos in [ANet-Captions](https://cs.stanford.edu/people/ranjaykrishna/densevid/) or [YouCook2](http://youcook2.eecs.umich.edu/) are long and usually contain multiple events (each described by a single sentence). You can ignore them if you deal with a short video clip.
