### ISSUE TITLE
Language evaluation: segments in test_2 and val_2

### ISSUE THREAD

**Issue by sgarbanti** [facebookresearch/grounded-video-description#23]
I don't understand the reason because, for the language part, you evaluate your model consedering also segments in the "anet_entities_val_2.json" and "anet_entities_test_2.json" files, while generated captions are only about the segments in "anet_entities_val_1.json" and  "anet_entities_test_1.json".
I can't  can't make out the sense of evaluate a model on elements that it didn't processed, resulting in loss in performance scores.

Can you help me to understand this?

Thank you very much for your effort in this work.

**Comment by LuoweiZhou** [comment]
@sgarbanti This is just to be consistent with existing works (e.g., [DEM](https://arxiv.org/pdf/1705.00754.pdf) and [MT](https://arxiv.org/pdf/1804.00819.pdf)). Besides, in the DEM paper, the authors mention the high overlapping rate between the two sets of annotations (tIoU of 70.2%), so if two segments overlap by a large percentage, the caption outcome should be close to each other. But you're right, we could choose to avoid the unnecessary performance loss by only considering val_1 and test_1, just like what we did for grounding. Reporting both would be ideal.

**Comment by sgarbanti** [comment]
@LuoweiZhou Ok, thank you very much for your answer.
Just to know, is there a particular reason why you didn't generate captions for all segments?

**Comment by LuoweiZhou** [comment]
@sgarbanti We could, but since val_2 and test_2 have no bounding box annotations, we could not conduct any grounding evaluation. This is the main obstacle. In my opinion, like what you mentioned, a better way to evaluate given GT segments is to consider only val_1 and test_1 (or whatever file your prediction is based on) and the what-we-assumed [convention](https://github.com/ranjaykrishna/densevid_eval/blob/master/evaluate.py#L280) to evaluate on both files is kind of ill-posed. Therefore, we'd encourage you to report evaluation on both file as a fair comparison and at the same time on val/test_1 only for a more truthful outcome.
